/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class NativeSerialPort {
  constructor()
  /**
   * Open a serial port and start reading in a background thread.
   * The data_callback is called with (null, Buffer) on data or (Error, null) on error.
   */
  open(path: string, baudRate: number, dataCallback: ((err: Error | null, arg: Buffer) => any)): void
  /** Write bytes to the port asynchronously (off the main thread). */
  write(data: Buffer): Promise<unknown>
  /** Close the port and signal the background reader thread to exit. */
  close(): void
}

export declare function listPorts(): Array<PortInfo>

export interface PortInfo {
  path: string
  portType: string
}
